version: '3.8'

services:
  database:
    container_name: database
    image: postgres:13.0-alpine
    volumes:
      - database_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    container_name: web
    image: avnovikovsm/foodgram:latest
    restart: always
    ports:
     - "8001:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - database
    env_file:
      - ../.env

  frontend:
    container_name: frontend
    build: ../frontend
    links:
      - web
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: ngnix
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/backend/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  database_volume:
