# Generated by Django 3.2.16 on 2023-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='amount',
        ),
    ]
