# Generated by Django 3.2.16 on 2022-12-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_alter_favorites_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='user_recipe_shoping_cart',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_cart', to='foodgram.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_recipe_shopping_cart'),
        ),
    ]
