name: Foodgram workflow

on: [push]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    # if: github.ref == 'refs/heads/dev/workflows'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build image foodgram
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/foodgram:latest ~/work/foodgram-project-react/foodgram-project-react/backend/foodgram_project/
      - name: Push image foodgram to Docker Hub
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/foodgram:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }} 
          script: |
            sudo docker-compose -f infra/docker-compose.yaml stop
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foodgram:latest
            sudo docker-compose run -f infra/docker-compose.yaml up -d
